---
name: Test
"on": [push, pull_request]
jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    container:
      image: "ruby:${{ matrix.ruby }}"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5  # Centos 8
          - 2.6
          - 2.7
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install dependencies
        run: |
          gem install bundler --no-document
          bundle install

      - name: RSpec
        run: |
          bundle exec rspec
